#%RAML 1.0 Library

types:
  randomObject:
    type: object
    example: !include someExample.json
    properties:
      key1:
        type: object
        required: false
        properties:
          key11: string
      key2:
        type: object
        properties:
          key21?: string
      key3:
        type: object
        required: true
      properties:
        type: object
        required: false
